add homework 14
superpro2007/py88_Zhur pull request #3
Opened 2023-05-30 19:57 UTC by superpro2007

used psycopg2

2023-05-31 11:14 UTC, nicilytop-tms requested changes
Nice job except additional .gitignore 😎

2023-05-31 11:14 UTC, nicilytop-tms commented on homework_14/.gitignore
dont need it on each folder.. its enough to add gitignore on root directory

2023-05-31 11:14 UTC, nicilytop-tms commented on homework_14/.gitignore
lets remove it

2023-05-31 20:06 UTC, superpro2007 commented on homework_14/.gitignore
> lets remove it

done thx

2023-06-01 09:46 UTC, nicilytop-tms approved these changes

2023-06-01 17:38 UTC, merged